name: reorderables
description: Reorderable table, row, column, wrap, sliver list that allow drag and drop of their children.
version: 0.4.0
homepage: https://github.com/juliansteenbakker/flutter_reorderable

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
